import type { StoryBand } from '../state/types';

/** Neutral settings for unbanded moments, whispers in the record, and opening-only pages.
 * Authored independently of the fragment pool: never look ahead to find an illustration.
 * IDs belong to the existing save contract; this catalogue changes presentation only. */
export const STORY_SETTINGS: Readonly<Record<string, StoryBand>> = {
  'reed-banner': 'field',
  'goose-feathers': 'court',
  granaries: 'granary',
  'river-stakes': 'river',
  'counting-house': 'court',
  'dien-hong': 'crowd',
  orange: 'court',
  'sixty-five-citadels': 'crowd',
  'ride-the-wind': 'mountain',
  substitution: 'march',
  'borrowed-sword': 'river',
  slandered: 'court',
  trusted: 'court',
  'cham-engineer': 'border',
  assembly: 'court',
  'rice-riot': 'crowd',
  'no-heir': 'court',
  'eat-together': 'shrine',
  unpaid: 'march',
  'five-days': 'march',
  'ghost-south': 'border',
  'without-slaughter': 'border',
  delayer: 'mountain',
  sickness: 'granary',
  'mountain-water': 'river',
  'thanh-giong': 'field',
  'salt-road': 'coast',
  thirteenth: 'court',
  'dai-cao': 'court',
  'chieu-doi-do': 'court',
  'nam-quoc': 'shrine',
  'hich-tuong-si': 'march',
  'chi-lang': 'mountain',
  'than-toc': 'march',
  'hai-ba-trung': 'crowd',
  'tien-phat': 'border',
  'ho-guom': 'river',
  'no-than': 'court',
  'yet-kieu': 'river',
  'van-don': 'coast',
  'paper-money': 'court',
  'luy-thay': 'border',
  'van-mieu': 'court',
  'thu-do': 'court',
  'binh-trong': 'border',
  'khuc-thua-du': 'court',
  'the-dykes': 'river',
  'che-bong-nga': 'coast',
};

/** More specific settings where an older fragment never declared its own band. */
export const STORY_FRAGMENT_SETTINGS: Readonly<Record<string, StoryBand>> = {
  'reed-banner.his-men-would-build-it': 'border',
  'cham-engineer.drawing-in-the-dirt': 'field',
  'paper-money.the-markets-will-not-take-them': 'crowd',
  'paper-money.bronze-comes-back-out-of-the-walls': 'crowd',
  'binh-trong.the-rearguard-does-not-come-back': 'march',
  'binh-trong.they-offer-him-a-title': 'court',
  'binh-trong.rather-a-ghost-in-the-south': 'night',
  'binh-trong.he-comes-home-quiet': 'court',
  'khuc-thua-du.they-noticed-after-all': 'border',
  'the-dykes.the-water-comes-over-at-night': 'river',
  'the-dykes.the-banks-hold': 'river',
};
